version: '3.9'
services:
  file-provider:
    image: file-provider
    volumes:
      - ./src/main/resources/assets:/app/src/main/resources/assets
    depends_on:
      - postgresql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/file_provider?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 1000MB
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 1000MB
    ports:
      - "8080:8080"
    networks:
      - app-network
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: file_provider
    ports:
      - "5432:5432"
    networks:
      - app-network
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge